baseURL = 'https://ruben-jimenez.github.io/devops-portfolio/'
languageCode = 'en-us'
title = 'My DevOps Portfolio'
theme = 'anubis'

[params]
author = "Ruben Jimenez Uribe"
description = "DevOps | Automatización | CI/CD"
disableDisqus = true